[meta]
# site title, show in <title>
title = "PuGo"

# subtitle, words after title, in description
subtitle = "Just For Writing"

# print in html <meta>
keyword = "pugo,golang,static,site,generator"

# print in html <meta>
desc = "PuGo is a Simple Static Site Generator"

# build links for feed, sitemap
domain = "localhost"

# root path for site# if empty, build as http://{domain}/
root = "http://localhost:9899/"

# cover page for homepage
cover = "@media/cover.jpg"

# global language,
# its used in global posts and themes, unless pages set lang
lang = "en"


[[nav]]
link = "/guide"
title = "Guide"
i18n = "guide"
hover = "guide"
blank = true

[[nav]]
link = "/docs"
title = "Docs"
i18n = "docs"
hover = "docs"
blank = true

[[nav]]
link = "http://godoc.org/github.com/go-xiaohei/pugo"
title = "API"
i18n = "api"
hover = "api"
blank = true

[[nav]]
link = "/news"
title = "News"
i18n = "news"
hover = "news"
blank = true

[[author]]
name = "pugo"
email = ""
url = "http://pugo.io"
avatar = "@media/author.png"
bio = "the robot of pugo, who generates all default contents."

# comment settings
# please only set one value
# if multi values, it prints all comment iframes
[comment]
# disqus site name
disqus = ""
# duoshuo short name
duoshuo = ""

# analytics settings
# please only set one value
# if multi values, it prints all analytics codes
[analytics]
# google analytics, need as UA-XXXXX-Y
google = ""
# baidu analytics, need hash-code in hm.js?hash-code
baidu = ""
# Tencent Analytics, need your_sid in http://tajs.qq.com/stats?sId?SId=your_sid
tencent = ""

[build]
# disable_post disable to read & compile post data
disable_post = false
# disable_page disable to read & compile page data
disable_page = false
# post_dir set posts directory
post_dir = "post"
# page_dir set pages directory
page_dir = "page"
# media dir set media directory, based on source directory
media_dir = "media"
